version: '3'
services:
  prometheus:
    image: prometheus
    ports:
      - "9090:9090"
    links:
      - random

  random:
    image: random
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
