version: '3'
services:
  prometheus:
    build:
      context: .
    ports:
      - "9090:9090"
    links:
      - random

  random:
    build:
      context: .
      dockerfile: Dockerfile.random
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
